#pragma once

// ---- CONSTANT DEFINES -----
// These do not change due to compiler settings

#define ORG_NAME "ARI"

// -----

// ----- TESTING DEFINES -----
// These are the flags that change if testing is enabled
#ifdef TESTING
#    define APP_NAME                      "GBoy_TEST"
#    define CONFIG_DEFAULT_CORE_LOG_LEVEL LOG_FATAL
#endif
// -----

// ----- DEFAULT DEFINES ----
// If a define can be changed due to compiler settings, this is where the default values should be
// set

#ifndef APP_NAME
#    define APP_NAME "GBoy"
#endif

#define DEFAULT_LOG_LEVEL LOG_INFO
// -----

// ========== CALCULATED DEFINES ==========
// If not set explicitly, these are calculated from above defines.

// ----- SYSTEM LOG LEVELS -----
#ifndef CONFIG_CORE_SYSTEM_LOG_LEVEL
#    define CONFIG_CORE_SYSTEM_LOG_LEVEL DEFAULT_LOG_LEVEL
#endif

#ifndef CONFIG_MEMORY_SYSTEM_LOG_LEVEL
#    define CONFIG_MEMORY_SYSTEM_LOG_LEVEL DEFAULT_LOG_LEVEL
#endif

#ifndef CONFIG_DISPLAY_SYSTEM_LOG_LEVEL
#    define CONFIG_DISPLAY_SYSTEM_LOG_LEVEL DEFAULT_LOG_LEVEL
#endif
// -----

// ----- CORE MODULE LOG LEVELS -----
#ifndef CONFIG_GBOY_MODULE_LOG_LEVEL
#    define CONFIG_GBOY_MODULE_LOG_LEVEL CONFIG_CORE_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_DEBUGGER_MODULE_LOG_LEVEL
#    define CONFIG_DEBUGGER_MODULE_LOG_LEVEL CONFIG_CORE_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_CPU_MODULE_LOG_LEVEL
#    define CONFIG_CPU_MODULE_LOG_LEVEL CONFIG_CORE_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_PPU_MODULE_LOG_LEVEL
#    define CONFIG_PPU_MODULE_LOG_LEVEL CONFIG_CORE_SYSTEM_LOG_LEVEL
#endif
// -----

// ----- MEMORY MODULE LOG LEVELS -----
#ifndef CONFIG_MBC_MODULE_LOG_LEVEL
#    define CONFIG_MBC_MODULE_LOG_LEVEL CONFIG_MEMORY_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_DLD_MODULE_LOG_LEVEL
#    define CONFIG_DLD_MODULE_LOG_LEVEL CONFIG_MEMORY_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_MBC1_MODULE_LOG_LEVEL
#    define CONFIG_MBC1_MODULE_LOG_LEVEL CONFIG_MEMORY_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_CARTRIDGE_MODULE_LOG_LEVEL
#    define CONFIG_CARTRIDGE_MODULE_LOG_LEVEL CONFIG_MEMORY_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_MMU_MODULE_LOG_LEVEL
#    define CONFIG_MMU_MODULE_LOG_LEVEL CONFIG_MEMORY_SYSTEM_LOG_LEVEL
#endif
// -----

// ----- DISPLAY MODULE LOG LEVELS -----
#ifndef CONFIG_WINDOW_MODULE_LOG_LEVEL
#    define CONFIG_WINDOW_MODULE_LOG_LEVEL CONFIG_DISPLAY_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_TEXTURE_MODULE_LOG_LEVEL
#    define CONFIG_TEXTURE_MODULE_LOG_LEVEL CONFIG_DISPLAY_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_TEXTBOX_MODULE_LOG_LEVEL
#    define CONFIG_TEXTBOX_MODULE_LOG_LEVEL CONFIG_DISPLAY_SYSTEM_LOG_LEVEL
#endif

#ifndef CONFIG_RENDERER_MODULE_LOG_LEVEL
#    define CONFIG_RENDERER_MODULE_LOG_LEVEL CONFIG_DISPLAY_SYSTEM_LOG_LEVEL
#endif
// -----

#ifndef CONFIG_EVENT_MODULE_LOG_LEVEL
#    define CONFIG_EVENT_MODULE_LOG_LEVEL DEFAULT_LOG_LEVEL
#endif
// ==========
