#pragma once

#ifdef TESTING
#    define CONFIG_MBC_MODULE_LOG_LEVEL  LOG_FATAL
#    define CONFIG_DLD_MODULE_LOG_LEVEL  LOG_FATAL
#    define CONFIG_MBC1_MODULE_LOG_LEVEL LOG_FATAL
#else
#    define CONFIG_MBC_MODULE_LOG_LEVEL  LOG_INFO
#    define CONFIG_DLD_MODULE_LOG_LEVEL  LOG_INFO
#    define CONFIG_MBC1_MODULE_LOG_LEVEL LOG_INFO
#endif
